# Generated by Django 5.0.2 on 2024-03-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
